[package]
name = "testing-sc-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.testing-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.61.0"
git = "https://github.com/multiversx/mx-sdk-rs"
branch = "rc/v0.62"
default-features = false
