[package]
name = "router-mock"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/router_mock.rs"

[dependencies.multiversx-sc]
version = "0.50.3"

[dev-dependencies]
num-bigint = "0.4"

[dev-dependencies.multiversx-sc-scenario]
version = "0.50.3"
