[workspace]
members = [
  "chain-config",
  "chain-config/meta",
  "chain-factory",
  "chain-factory/meta",
  "esdt-safe",
  "esdt-safe/meta",
  "fee-market",
  "fee-market/meta",
  "pair-mock",
  "pair-mock/meta",
  "router-mock",
  "router-mock/meta",
  "header-verifier",
  "header-verifier/meta", 
  "enshrine-esdt-safe",
  "enshrine-esdt-safe/meta",
  "token-handler",
  "token-handler/meta",
]
