[contracts.main]
name = "sov-esdt-safe"
allocator = "static64k"

[contracts.view]
name = "sov-esdt-safe-view"
external-view = true
add-unlabelled = false
add-labels = ["sov-esdt-safe-external-view"]

[[proxy]]
path = "../common/proxies/src/sov_esdt_safe_proxy.rs"
