[contracts.main]
name = "sov-fee-market"

[contracts.full]
name = "sov-fee-market"
add-unlabelled = true
add-labels = ["sov-fee-market-external-view"]

[contracts.view]
name = "sov-fee-market-view"
external-view = true
add-unlabelled = false
add-labels = ["sov-fee-market-external-view"]

[[proxy]]
path = "../common/proxies/src/sov_fee_market_proxy.rs"
