[package]
name = "cross-chain"
version = "0.1.0"
authors = ["you"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"

[dependencies.multiversx-sc-modules]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"

[dependencies.structs]
path = "../structs"

[dependencies.proxies]
path = "../proxies"

[dependencies.utils]
path = "../utils"

[dependencies.error-messages]
path = "../error-messages"

[dependencies.custom-events]
path = "../custom-events"
