[package]
name = "cross-chain"
version = "0.1.0"
authors = ["you"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.62.0"
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "d23fc3b6834925e68c25eb7622efb2e2c3344d15"

[dependencies.multiversx-sc-modules]
version = "0.62.0"
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "d23fc3b6834925e68c25eb7622efb2e2c3344d15"

[dependencies.structs]
path = "../structs"

[dependencies.proxies]
path = "../proxies"

[dependencies.common-utils]
path = "../common-utils"

[dependencies.error-messages]
path = "../error-messages"

[dependencies.custom-events]
path = "../custom-events"
