[package]
name = "common-utils"
version = "0.1.0"
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.structs]
path = "../structs"

[dependencies.error-messages]
path = "../error-messages"

[dependencies.proxies]
path = "../proxies"

[dependencies.custom-events]
path = "../custom-events"

[dependencies.multiversx-sc]
version = "0.61.0"
git = "https://github.com/multiversx/mx-sdk-rs"
features = ["esdt-token-payment-legacy-decode"]
branch = "rc/v0.62"
