[package]
name = "sovereign-forge-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.sovereign-forge]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
default-features = false
