[package]
name = "chain-factory-meta"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.chain-factory]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.61.0"
