[package]
name = "chain-factory-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.chain-factory]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.46.1"
