[package]
name = "router-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.router-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.0"
default-features = false
