[package]
name = "chain-config-meta"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.chain-config]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"
