[package]
name = "chain-config-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dependencies.chain-config]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.52.3"
