[package]
name = "mvx-esdt-safe-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.mvx-esdt-safe]
path = ".."

[dependencies.multiversx-sc-meta-lib]
default-features = false
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"
