[package]
name = "mvx-esdt-safe-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.mvx-esdt-safe]
path = ".."

[dependencies.multiversx-sc-meta-lib]
default-features = false
version = "0.63.0"
