[package]
name = "token-whitelist"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[dependencies.bls-signature]
path = "../bls-signature"

[dependencies.setup-phase]
path = "../setup-phase"

[dependencies.utils]
path = "../utils"

[dependencies.multiversx-sc]
version = "=0.50.3"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.50.3"
