[package]
name = "mvx-fee-market-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.mvx-fee-market]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"
default-features = false
