[package]
name = "chain-config"
version = "0.1.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.60.0"

[dev-dependencies.common-test-setup]
path = "../common/common-test-setup"

[dependencies.multiversx-sc]
version = "=0.60.0"

[dependencies.multiversx-sc-modules]
version = "=0.60.0"

[dependencies.structs]
path = "../common/structs"

[dependencies.proxies]
path = "../common/proxies"

[dependencies.setup-phase]
path = "../common/setup-phase"

[dependencies.error-messages]
path = "../common/error-messages"

[dependencies.cross-chain]
path = "../common/cross-chain"

[dependencies.events]
path = "../common/events"

[dependencies.utils]
path = "../common/utils"
