[package]
name = "tx-batch-module"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[dependencies.multiversx-sc]
version = "=0.54.5"

[dependencies.transaction]
path = "../transaction"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.54.5"
