[package]
name = "tx-nonce"
version = "0.1.0"
authors = ["andrei-baltariu <andrei.baltariu@multiversx.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.61.0"
git = "https://github.com/multiversx/mx-sdk-rs"
branch = "rc/v0.62"

[dependencies.structs]
path = "../structs"
