[package]
name = "token-handler-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.token-handler]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.52.2"
default-features = false
