[package]
name = "setup-phase"
version = "0.1.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[dependencies.multiversx-sc]
version = "=0.60.0"

[dependencies.error-messages]
path = "../error-messages"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.60.0"
