[package]
name = "setup-phase"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[dependencies.multiversx-sc]
version = "=0.54.3"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.54.3"
