[package]
name = "setup-phase"
version = "0.1.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[dependencies.multiversx-sc]
version = "0.61.0"
git = "https://github.com/multiversx/mx-sdk-rs"
branch = "rc/v0.62"

[dependencies.error-messages]
path = "../error-messages"

[dependencies.common-utils]
path = "../common-utils"

[dependencies.custom-events]
path = "../custom-events"

[dev-dependencies.multiversx-sc-scenario]
version = "0.61.0"
git = "https://github.com/multiversx/mx-sdk-rs"
branch = "rc/v0.62"
