[package]
name = "setup-phase"
version = "0.1.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2021"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"

[dependencies.error-messages]
path = "../error-messages"

[dependencies.utils]
path = "../utils"

[dependencies.custom-events]
path = "../custom-events"

[dev-dependencies.multiversx-sc-scenario]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"
