[package]
name = "header-verifier-meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies.header-verifier]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.63.0"
default-features = false
