[package]
name = "proxies"
version = "0.1.0"
edition = "2021"

[dependencies.multiversx-sc]
git = "https://github.com/multiversx/mx-sdk-rs"
rev = "b59411841984a2fcbf76498d29bc131f2d433af9"

[dependencies.structs]
path = "../structs"
