[package]
name = "bls-signature"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@multiversx.com>"]
edition = "2018"

[dependencies.multiversx-sc]
version = "=0.53.2"

[dependencies.transaction]
path = "../transaction"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.53.2"
