[package]
name = "fee-market-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.fee-market]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.49.0"
default-features = false
